### PR TITLE
cmake source for deoeplete

### PR DESCRIPTION
**Pull request by kiddos**
hi
I wrote this cmake source for completing cmake commands and variables
hope you will like it and add this to your project

### CODE REVIEW

**Comment by zchee** [comment]
@kiddos Thanks pull request! and sorry for late reply.
I know you `deoplete-cpp`, it's great! Maybe it's target similar deoplete-clang, but solved some of the implements.

But port to my project...? I'm happy, but why?

Anyway, `cmake` source seems to LGTM. will try test it :)

**Comment by kiddos** [comment]
I am thinking if I can merge some of mine implementation to your project. I add a lot of cache to make completion go faster. And I actually trick deoplete to believe cuda and arduino source are c++. 
But I am experiencing some libclang version problem. I got a opensuse laptop where it only distribute libclang 3.7. I try with libclang-py3 3.8.0 . It worked but it's tricky to install. I want to make it easier to install , like more people would want to use deoplete.

**Comment by zchee** [comment]
@kiddos Thanks for reply, and understand your thinking plan.
I will tell the project of the plan to you later.

**Comment by zchee** [comment]
@kiddos Thanks for reply and understand your thinking plan.

Yeah, some linux distro has different libclang versions. It will be confusing users.
I will tell the project of the plan to you later.

**Comment by zchee** [comment]
@kiddos Sorry for late reply :(
will check it, please wait a moment 🙏

**Comment by zchee** [comment]
@kiddos Sorry for the late reply.
It seems works fine :) I will merge it.

**Comment by zchee** [comment]
@kiddos BTW, I develop C family complete engine with a new approach.
It makes the rpc daemon and parses all of related to C file, and communicates over the msgpack.
If you interesting in it, I will invite you to my private repository.
WDYT?

**Comment by kiddos** [comment]
Cool. I am interested. I was thinking of doing that too.

**Pull request merged**
