### PR TITLE
Support for absolute path for compilation database

### PR DESCRIPTION
**Pull request by Moeryn**
When the compilation_database was loaded from the .clang it was working only for a relative path.

### CODE REVIEW

**Comment by zchee** [comment]
@Moeryn Thanks for pull request!
I will test it :)

**Comment by Shougo** [comment]
The code only supports Unix...
It should support Windows path pattern.

**Comment by zchee** [comment]
@Shougo Thanks point out!
It seems @Moeryn has been fixed use `os.path.isabs()`
PTAL.

**Comment by zchee** [comment]
@Moeryn merged. Thanks! :)

**Pull request merged**
